#!/usr/bin/python3

import argparse
import sys
import bs4
import configparser
import requests
from xdg import BaseDirectory

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("category", nargs="?")
    args = parser.parse_args()
    display_fortune(category=args.category)

def display_fortune(category=None):
    config_path = BaseDirectory.load_first_config("pyfortunes.cfg")
    if not config_path:
        sys.exit("pyfortunes.cfg not found")
    config = configparser.ConfigParser()
    config.read(config_path)
    url = config["server"]["url"]
    url = url + "/fortune"
    if category:
        url += "/%s" % category
    as_html = requests.get(url).text
    soup = bs4.BeautifulSoup(as_html, "html.parser")
    pre = soup.find("pre").text
    # remove leading \n
    print(pre[1:], end="")
    ref = soup.find("a").text
    print(ref.strip())

if __name__ == "__main__":
    main()
